Hoàn thiện quy trình

diff --git a/.github/workflows/dast.yml b/.github/workflows/dast.yml
--- a/.github/workflows/dast.yml
+++ b/.github/workflows/dast.yml
@@ -2,53 +2,118 @@ name: DAST Baseline Scan
 
 on:
   push:
-    branches: [ "main" , "dev_vu", "fix_hung" ]
+    branches:
+      - '**'
+  pull_request:
+    branches:
+      - '**'
+  workflow_dispatch: # Để chạy thủ công
 
 jobs:
-  zap_scan:
+  zap_baseline_scan:
     runs-on: ubuntu-latest
-    name: Quy trình Kiểm duyệt DAST Tự động
-
+    name: Quy trình kiểm duyệt DAST baseline-scan Tự động
+    
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          MYSQL_ROOT_PASSWORD: root
+          MYSQL_DATABASE: microshop_db
+        ports:
+          - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
     steps:
-
-      - name: 1. Checkout source
+      - name: 1. Tải code từ GitHub về máy ảo
         uses: actions/checkout@v4
 
-      - name: 2. Setup Java 21
+      - name: 2. Import database schema và mock data
+        run: |
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/database_schema.sql
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/root_data.sql
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/mock_ff.sql
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/mock_lq.sql
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/mock_riot.sql
+          mysql -h 127.0.0.1 -u root -proot microshop_db < database/mock_steam_game.sql
+      - name: 3. Chỉnh sửa context.xml cho môi trường Linux
+        run: sed -i 's|C:/Users/os/Desktop/microshop_uploads|/tmp/microshop_uploads|g' src/main/webapp/META-INF/context.xml
+
+      - name: 4. Cài đặt môi trường Java 21
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
           cache: maven
 
-      - name: 3. Build WAR (Maven)
+      - name: 5. Biên dịch code thành file .war
         run: mvn clean package -DskipTests
 
-      - name: 4. Build Docker image
+      - name: 6. Đóng gói Docker Image
         run: docker build -t micro-shop-app .
 
-      - name: 5. Run container
+      - name: 7. Khởi chạy ứng dụng
         run: |
           docker run -d -p 8080:8080 --name micro-shop-test micro-shop-app
-          echo "Waiting for application..."
-          until curl -s http://localhost:8080/microShop > /dev/null; do
-            sleep 5
-          done
-          echo "Application is ready"
+          sleep 40 
+      - name: 8. Phân quyền lại thư mục cho ZAP
+        run: chmod -R 777 $GITHUB_WORKSPACE
 
-      - name: 6. Run OWASP ZAP Baseline Scan
-        uses: zaproxy/action-baseline@v0.12.0
-        with:
-          target: 'http://localhost:8080/microShop'
-          issue_title: 'Kết quả kiểm duyệt DAST - Baseline'
-          cmd_options: '-J zap-report.json'
-          fail_action: false
+      - name: Pull ZAP docker image
+        run: docker pull ghcr.io/zaproxy/zaproxy:stable
 
-      - name: 7. Debug files
-        run: ls -la
-
-      - name: 8. Save baseline report
+      - name: 9. Chạy OWASP ZAP baseline-scan
+        run: |
+          docker run --network host \
+          -v $(pwd):/zap/wrk/:rw \
+          ghcr.io/zaproxy/zaproxy:stable \
+          zap-baseline.py \
+          -t http://localhost:8080/ \
+          -J report_json.json \
+          -r report_html.html \
+          -w report_md.md \
+          -c security/zap-baseline.conf \
+          -i security/zap-baseline.ignore \
+          -I \
+          -a || true
+      - name: 10. Quality Gate - Kiểm tra rủi ro Baseline
+        run: |
+          echo "Đánh giá Quality Gate..."
+          
+          if [ ! -f report_json.json ]; then
+            echo "Lỗi: Không tìm thấy báo cáo report_json.json.!"
+            exit 1
+          fi
+          
+          # Đếm số lượng rủi ro theo mức độ
+          CRITICAL_ALERTS=$(jq '[.site[].alerts[]? | select(.riskcode=="4")] | length' report_json.json || echo "0")
+          HIGH_ALERTS=$(jq '[.site[].alerts[]? | select(.riskcode=="3")] | length' report_json.json || echo "0")
+          
+          # Ép kiểu để tránh lỗi cú pháp Bash
+          CRITICAL_ALERTS=${CRITICAL_ALERTS:-0}
+          HIGH_ALERTS=${HIGH_ALERTS:-0}
+          
+          echo "=================================="
+          echo "Số lỗ hổng CRITICAL : $CRITICAL_ALERTS"
+          echo "Số lỗ hổng HIGH     : $HIGH_ALERTS"
+          echo "=================================="
+          
+          # Chốt chặn: Fail nếu có bất kỳ lỗi HIGH hoặc CRITICAL nào
+          if [ "$CRITICAL_ALERTS" -gt 0 ] || [ "$HIGH_ALERTS" -gt 0 ]; then
+            echo "QUALITY GATE FAILED: Phát hiện lỗi nghiêm trọng (HIGH/CRITICAL) tại baseline-scan!"
+            exit 1
+          else
+            echo "QUALITY GATE PASSED!"
+          fi
+      - name: 11. Lưu trữ báo cáo baseline-scan
         uses: actions/upload-artifact@v4
+        if: always()
         with:
-          name: zap-baseline
-          path: zap-report.json
+          name: zap-baseline-report
+          path: |
+            report_json.json
+            report_html.html
+            report_md.md
